import { createRequire } from 'node:module';
import { readFileSync } from 'node:fs';
import path from 'node:path';
const require=createRequire(import.meta.url);
const { chromium }=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const directory=process.argv[2];
if(!directory)throw Error('Pass the disposable test data directory');
const info=JSON.parse(readFileSync(path.join(directory,'runtime.json'),'utf8'));
const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'});
const errors=[];
try{
 const page=await browser.newPage({viewport:{width:1400,height:950}});
 page.on('pageerror',error=>errors.push(error.message));
 await page.goto(info.origin+'/#'+info.token);
 await page.getByRole('heading',{name:'Receipts',exact:true}).waitFor();
 await page.getByRole('button',{name:'Add receipt',exact:true}).click();
 await page.getByLabel('Merchant',{exact:true}).fill('Browser smoke receipt');
 await page.getByLabel('Date',{exact:true}).fill('2026-09-08');
 await page.getByLabel('Total',{exact:true}).fill('6.90');
 await page.getByRole('button',{name:'Save receipt',exact:true}).click();
 await page.getByRole('button',{name:'Browser smoke receipt',exact:true}).waitFor();
 await page.screenshot({path:path.join(directory,'desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'Browser smoke receipt',exact:true}).click();
 await page.getByLabel('Total',{exact:true}).fill('7.90');
 await page.getByRole('button',{name:'Save receipt',exact:true}).click();
 await page.getByRole('cell',{name:'€7.90',exact:true}).waitFor();
 await page.getByRole('button',{name:'Collections',exact:true}).click();
 await page.getByRole('textbox',{name:'Name',exact:true}).fill('Smoke collection');
 await page.getByRole('button',{name:'Create collection',exact:true}).click();
 await page.getByText('Smoke collection',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Budget',exact:true}).click();
 await page.getByLabel('Monthly limit').fill('150');
 await page.getByLabel('Yearly limit').fill('1800');
 await page.getByLabel('Enable budget').check();
 await page.getByRole('button',{name:'Save budget',exact:true}).click();
 await page.getByRole('button',{name:'Local settings',exact:true}).click();
 await page.getByRole('button',{name:'Create backup',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Backup saved:'}).waitFor();
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Receipts',exact:true}).click();
 await page.getByRole('button',{name:'Browser smoke receipt',exact:true}).waitFor();
 await page.screenshot({path:path.join(directory,'mobile.png'),fullPage:true});
 await page.getByRole('button',{name:'Browser smoke receipt',exact:true}).click();
 page.once('dialog',dialog=>dialog.accept());
 await page.getByRole('button',{name:'Delete receipt',exact:true}).click();
 await page.getByRole('heading',{name:'Your receipts, in one place'}).waitFor();
 if(errors.length)throw Error(errors.join('\n'));
 console.log('Browser CRUD, collection creation, budget save, backup, responsive screenshots: passed');
}finally{await browser.close()}
